---
bigbluebutton:
  secret: 0ol5t44UR21rrP0xL5ou7IBFumWF3GENebgW1RyTfbU
  recordingsPollInterval: 1m
balancer:
  metricsRange: -5m
  cpuLimit: 99
  memLimit: 99
admin:
  apiKey: kgpqrTipM2yjcXwz5pOxBKViE9oNX76R
port: 8090
timescale:
  user: bigblueswarm
  password: password
  database: bigblueswarm
monitoring:
  auth: password
  port: 8091
  aggregation_interval: 10s
