version: '3.8'
services:
  b3lb:
    container_name: b3lb
    image: sledunois/b3lb:v2.1.1
    links:
      - redis
      - bbb1
      - bbb2
      - influxdb
      - nconfig
    ports:
      - "8090:8090"
    volumes:
      - ./config.yml:/config.yml
    command: -config consul:http://nconfig:8500
