version: '3.8'
services:
  nconfig:
    container_name: consul
    image: consul:1.15.4
    ports:
      - "8500:8500"
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0