version: '3.8'
services:
  bbb1:
    container_name: bbb1
    image: sledunois/bbb-dev:2.4-develop
    privileged: true
    ports:
      - "8081:80"
    links:
      - timescale
  bbb2:
    container_name: bbb2
    image: sledunois/bbb-dev:2.4-develop
    privileged: true
    ports:
      - "8080:80"
    links:
      - timescale
  timescale:
    container_name: timescale
    image: timescale/timescaledb:latest-pg15
    environment:
      - POSTGRES_USER=bigblueswarm
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bigblueswarm
    ports:
      - "5432:5432"
