version: '3.8'
services:
  bigblueswarm:
    container_name: bigblueswarm
    image: sledunois/bigblueswarm:latest
    links:
      - redis
      - bbb1
      - bbb2
      - influxdb
      - nconfig
    ports:
      - "8090:8090"
    volumes:
      - ./config.yml:/config.yml
    command: -config consul:http://nconfig:8500
